import { TableData } from '../types/table.types';
import {
  lucideInfo,
  lucideTerminal,
  lucideCog,
  lucidePlus,
  lucidePause,
  lucideDownload,
  lucideTrash2,
} from '@ng-icons/lucide';

export const TABLE_DATA: TableData[] = [
  {
    id: 'cls-001',
    cluster_name: 'Production-Main',
    status: 1,
    workloads: 24,
    nodes: 5,
    cpu_usage: 28,
    memory_usage: 15,
  },
  {
    id: 'cls-002',
    cluster_name: 'Development',
    status: -1,
    workloads: 12,
    nodes: 3,
    cpu_usage: 65,
    memory_usage: 38,
  },
  {
    id: 'cls-003',
    cluster_name: 'Testing',
    status: 0, // inactive
    workloads: 8,
    nodes: 2,
    cpu_usage: 20,
    memory_usage: 90,
  },
  {
    id: 'cls-004',
    cluster_name: 'Staging',
    status: -2,
    workloads: 18,
    nodes: 4,
    cpu_usage: 62,
    memory_usage: 55,
  },
  {
    id: 'cls-005',
    cluster_name: 'Analytics',
    status: 2, // error
    workloads: 6,
    nodes: 3,
    cpu_usage: 90,
    memory_usage: 95,
  },
  {
    id: 'cls-006',
    cluster_name: 'Data-Processing',
    status: 1,
    workloads: 32,
    nodes: 8,
    cpu_usage: 75,
    memory_usage: 80,
  },
  {
    id: 'cls-007',
    cluster_name: 'Backup',
    status: 0, // inactive
    workloads: 4,
    nodes: 2,
    cpu_usage: 10,
    memory_usage: 12,
  },
  {
    id: 'cls-008',
    cluster_name: 'ML-Training',
    status: 1,
    workloads: 16,
    nodes: 6,
    cpu_usage: 88,
    memory_usage: 92,
  },
  {
    id: 'cls-009',
    cluster_name: 'Web-Frontend',
    status: 1,
    workloads: 10,
    nodes: 3,
    cpu_usage: 55,
    memory_usage: 48,
  },
  {
    id: 'cls-010',
    cluster_name: 'API-Backend',
    status: 2, // error
    workloads: 14,
    nodes: 4,
    cpu_usage: 95,
    memory_usage: 85,
  },
  {
    id: 'cls-011',
    cluster_name: 'Database',
    status: 1,
    workloads: 8,
    nodes: 5,
    cpu_usage: 72,
    memory_usage: 68,
  },
  {
    id: 'cls-012',
    cluster_name: 'Monitoring',
    status: 1,
    workloads: 6,
    nodes: 2,
    cpu_usage: 40,
    memory_usage: 35,
  },
  {
    id: 'cls-013',
    cluster_name: 'Security',
    status: 0, // inactive
    workloads: 5,
    nodes: 2,
    cpu_usage: 15,
    memory_usage: 18,
  },
  {
    id: 'cls-014',
    cluster_name: 'Logging',
    status: 1,
    workloads: 7,
    nodes: 3,
    cpu_usage: 50,
    memory_usage: 45,
  },
  {
    id: 'cls-015',
    cluster_name: 'CI-CD',
    status: 1,
    workloads: 12,
    nodes: 4,
    cpu_usage: 65,
    memory_usage: 60,
  },
  {
    id: 'cls-016',
    cluster_name: 'Microservices',
    status: 2, // error
    workloads: 28,
    nodes: 7,
    cpu_usage: 92,
    memory_usage: 88,
  },
  {
    id: 'cls-017',
    cluster_name: 'Cache',
    status: 1,
    workloads: 4,
    nodes: 2,
    cpu_usage: 58,
    memory_usage: 52,
  },
  {
    id: 'cls-018',
    cluster_name: 'Message-Queue',
    status: 1,
    workloads: 9,
    nodes: 3,
    cpu_usage: 70,
    memory_usage: 65,
  },
  {
    id: 'cls-019',
    cluster_name: 'Storage',
    status: 0, // inactive
    workloads: 6,
    nodes: 4,
    cpu_usage: 25,
    memory_usage: 30,
  },
  {
    id: 'cls-020',
    cluster_name: 'Gateway',
    status: 1,
    workloads: 8,
    nodes: 3,
    cpu_usage: 60,
    memory_usage: 55,
  },
];

export const ACTION_ICONS: Record<string, string> = {
  view_details: lucideInfo,
  view_logs: lucideTerminal,
  scale_cluster: lucideCog,
  add_nodes: lucidePlus,
  cordon_cluster: lucidePause,
  drain_cluster: lucideDownload,
  delete_cluster: lucideTrash2,
};